export default {
  login: "bisoladev",
  id: 62376395,
  node_id: "MDQ6VXNlcjYyMzc2Mzk1",
  avatar_url: "https://avatars.githubusercontent.com/u/62376395?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bisoladev",
  html_url: "https://github.com/bisoladev",
  followers_url: "https://api.github.com/users/bisoladev/followers",
  following_url:
    "https://api.github.com/users/bisoladev/following{/other_user}",
  gists_url: "https://api.github.com/users/bisoladev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/bisoladev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bisoladev/subscriptions",
  organizations_url: "https://api.github.com/users/bisoladev/orgs",
  repos_url: "https://api.github.com/users/bisoladev/repos",
  events_url: "https://api.github.com/users/bisoladev/events{/privacy}",
  received_events_url: "https://api.github.com/users/bisoladev/received_events",
  type: "User",
  site_admin: false,
  name: "Bisola Onaolapo",
  company: null,
  blog: "https://bisola.com.ng/",
  location: "Nigeria, Lagos",
  email: null,
  hireable: true,
  bio:
    "I am a Frontend developer, interested in learning and creating solutions.",
  twitter_username: "bisolaDev",
  public_repos: 47,
  public_gists: 0,
  followers: 8,
  following: 9,
  created_at: "2020-03-19T08:37:16Z",
  updated_at: "2022-11-01T16:59:02Z",
};
