export default [
  {
    login: "franklinobiukwu",
    id: 22842390,
    node_id: "MDQ6VXNlcjIyODQyMzkw",
    avatar_url: "https://avatars.githubusercontent.com/u/22842390?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/franklinobiukwu",
    html_url: "https://github.com/franklinobiukwu",
    followers_url: "https://api.github.com/users/franklinobiukwu/followers",
    following_url:
      "https://api.github.com/users/franklinobiukwu/following{/other_user}",
    gists_url: "https://api.github.com/users/franklinobiukwu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/franklinobiukwu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/franklinobiukwu/subscriptions",
    organizations_url: "https://api.github.com/users/franklinobiukwu/orgs",
    repos_url: "https://api.github.com/users/franklinobiukwu/repos",
    events_url: "https://api.github.com/users/franklinobiukwu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/franklinobiukwu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "DincerDogan",
    id: 25222703,
    node_id: "MDQ6VXNlcjI1MjIyNzAz",
    avatar_url: "https://avatars.githubusercontent.com/u/25222703?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/DincerDogan",
    html_url: "https://github.com/DincerDogan",
    followers_url: "https://api.github.com/users/DincerDogan/followers",
    following_url:
      "https://api.github.com/users/DincerDogan/following{/other_user}",
    gists_url: "https://api.github.com/users/DincerDogan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/DincerDogan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/DincerDogan/subscriptions",
    organizations_url: "https://api.github.com/users/DincerDogan/orgs",
    repos_url: "https://api.github.com/users/DincerDogan/repos",
    events_url: "https://api.github.com/users/DincerDogan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/DincerDogan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "codewarsfx",
    id: 41517041,
    node_id: "MDQ6VXNlcjQxNTE3MDQx",
    avatar_url: "https://avatars.githubusercontent.com/u/41517041?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/codewarsfx",
    html_url: "https://github.com/codewarsfx",
    followers_url: "https://api.github.com/users/codewarsfx/followers",
    following_url:
      "https://api.github.com/users/codewarsfx/following{/other_user}",
    gists_url: "https://api.github.com/users/codewarsfx/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/codewarsfx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/codewarsfx/subscriptions",
    organizations_url: "https://api.github.com/users/codewarsfx/orgs",
    repos_url: "https://api.github.com/users/codewarsfx/repos",
    events_url: "https://api.github.com/users/codewarsfx/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/codewarsfx/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "emmanuelkolawole4",
    id: 50505707,
    node_id: "MDQ6VXNlcjUwNTA1NzA3",
    avatar_url: "https://avatars.githubusercontent.com/u/50505707?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/emmanuelkolawole4",
    html_url: "https://github.com/emmanuelkolawole4",
    followers_url: "https://api.github.com/users/emmanuelkolawole4/followers",
    following_url:
      "https://api.github.com/users/emmanuelkolawole4/following{/other_user}",
    gists_url: "https://api.github.com/users/emmanuelkolawole4/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/emmanuelkolawole4/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/emmanuelkolawole4/subscriptions",
    organizations_url: "https://api.github.com/users/emmanuelkolawole4/orgs",
    repos_url: "https://api.github.com/users/emmanuelkolawole4/repos",
    events_url:
      "https://api.github.com/users/emmanuelkolawole4/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/emmanuelkolawole4/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "adisamicheal",
    id: 50669175,
    node_id: "MDQ6VXNlcjUwNjY5MTc1",
    avatar_url: "https://avatars.githubusercontent.com/u/50669175?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/adisamicheal",
    html_url: "https://github.com/adisamicheal",
    followers_url: "https://api.github.com/users/adisamicheal/followers",
    following_url:
      "https://api.github.com/users/adisamicheal/following{/other_user}",
    gists_url: "https://api.github.com/users/adisamicheal/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/adisamicheal/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/adisamicheal/subscriptions",
    organizations_url: "https://api.github.com/users/adisamicheal/orgs",
    repos_url: "https://api.github.com/users/adisamicheal/repos",
    events_url: "https://api.github.com/users/adisamicheal/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/adisamicheal/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "taiwoyewole",
    id: 56822133,
    node_id: "MDQ6VXNlcjU2ODIyMTMz",
    avatar_url: "https://avatars.githubusercontent.com/u/56822133?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/taiwoyewole",
    html_url: "https://github.com/taiwoyewole",
    followers_url: "https://api.github.com/users/taiwoyewole/followers",
    following_url:
      "https://api.github.com/users/taiwoyewole/following{/other_user}",
    gists_url: "https://api.github.com/users/taiwoyewole/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/taiwoyewole/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/taiwoyewole/subscriptions",
    organizations_url: "https://api.github.com/users/taiwoyewole/orgs",
    repos_url: "https://api.github.com/users/taiwoyewole/repos",
    events_url: "https://api.github.com/users/taiwoyewole/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/taiwoyewole/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bcjcodes",
    id: 61957905,
    node_id: "MDQ6VXNlcjYxOTU3OTA1",
    avatar_url: "https://avatars.githubusercontent.com/u/61957905?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bcjcodes",
    html_url: "https://github.com/bcjcodes",
    followers_url: "https://api.github.com/users/bcjcodes/followers",
    following_url:
      "https://api.github.com/users/bcjcodes/following{/other_user}",
    gists_url: "https://api.github.com/users/bcjcodes/gists{/gist_id}",
    starred_url: "https://api.github.com/users/bcjcodes/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bcjcodes/subscriptions",
    organizations_url: "https://api.github.com/users/bcjcodes/orgs",
    repos_url: "https://api.github.com/users/bcjcodes/repos",
    events_url: "https://api.github.com/users/bcjcodes/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bcjcodes/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dvlapo",
    id: 80985036,
    node_id: "MDQ6VXNlcjgwOTg1MDM2",
    avatar_url: "https://avatars.githubusercontent.com/u/80985036?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dvlapo",
    html_url: "https://github.com/dvlapo",
    followers_url: "https://api.github.com/users/dvlapo/followers",
    following_url: "https://api.github.com/users/dvlapo/following{/other_user}",
    gists_url: "https://api.github.com/users/dvlapo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dvlapo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dvlapo/subscriptions",
    organizations_url: "https://api.github.com/users/dvlapo/orgs",
    repos_url: "https://api.github.com/users/dvlapo/repos",
    events_url: "https://api.github.com/users/dvlapo/events{/privacy}",
    received_events_url: "https://api.github.com/users/dvlapo/received_events",
    type: "User",
    site_admin: false,
  },
];
